### ISSUE TITLE
httpx.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by KraxelHuber** [foxmask/joplin-api#11]
I am sending quite a lot of notes (incl. attachments) via the Joplin-API to the Joplin app. At some point (after more than 1,000 notes successfully saved), I do get a `httpx.exceptions.ReadTimeout`. This timeout occures always at a specific note. However, this particular note is not different from other notes that have been saved successfully.

Do you have an idea, by any chance, what is going on?

```
Traceback (most recent call last):
  File "/home/andi/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/andi/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/andi/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/andi/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/andi/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/andi/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/andi/coding/notestation_to_joplin/notestation_to_joplin/nsx2joplin.py", line 372, in <module>
    nsx.export_to_joplin(token=joplin_token, nsx_content=nsx_content)
  File "/home/andi/coding/notestation_to_joplin/notestation_to_joplin/nsx2joplin.py", line 329, in export_to_joplin
    note["content"] = asyncio.run(
  File "/home/andi/.pyenv/versions/3.8.1/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/andi/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/home/andi/coding/notestation_to_joplin/notestation_to_joplin/nsx2joplin.py", line 273, in create_resource
    res = await joplin.create_resource(
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/joplin_api/core.py", line 459, in create_resource
    return await self.query('post', '/resources/', **data)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/joplin_api/core.py", line 96, in query
    res = await client.post(self.JOPLIN_HOST + '/resources',
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/client.py", line 1305, in post
    return await self.request(
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/client.py", line 1096, in request
    response = await self.send(
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/client.py", line 1117, in send
    response = await self.send_handling_redirects(
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/client.py", line 1147, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/client.py", line 1184, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/client.py", line 1208, in send_single_request
    response = await dispatcher.send(request, timeout=timeout)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 157, in send
    raise exc
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/dispatch/connection_pool.py", line 153, in send
    response = await connection.send(request, timeout=timeout)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/dispatch/connection.py", line 44, in send
    return await self.connection.send(request, timeout=timeout)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/dispatch/http11.py", line 52, in send
    http_version, status_code, headers = await self._receive_response(timeout)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/dispatch/http11.py", line 127, in _receive_response
    event = await self._receive_event(timeout)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/dispatch/http11.py", line 174, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/home/andi/.local/share/virtualenvs/notestation_to_joplin-Ps2Gtwj0/lib/python3.8/site-packages/httpx/backends/asyncio.py", line 134, in read
    raise ReadTimeout() from None
httpx.exceptions.ReadTimeout
```

**Comment by foxmask** [comment]
The only thing that comes to my mind is that the webclipper service crashs like if it was a DoS. May be it is too fragile.
Did you try to make bulk creation and put a sleep for each 1000 notes for example to let it take a breath.

**Comment by KraxelHuber** [comment]
I put in a sleep after every other 500 notes. This did the trick.

**Comment by foxmask** [comment]
good. :) I will try to manage the Vue store better to avoid that behaviour
